config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  resources :user_stocks, only: [:create, :destroy]
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :ticker, :name, presence: true

  # Look up a stock based on the ticker symbol using the IEX Finance API and return a new instance of Stock or nil
  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key], 
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      new(
        ticker: ticker_symbol, 
        name: client.company(ticker_symbol).company_name, 
        last_price: client.price(ticker_symbol)
      )
    rescue => exception
      return nil
    end
  end

  # Check the database to know if the stock already exists or not in the table
  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # Methods to check if the user can track a new stock

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end
  
  # Connect to the IEX Finance API, go through each of the user's stocks, and update the stock's prices
  def update_stock_prices
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key], 
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      stocks.each do |stock|
        stock.last_price = client.price(stock.ticker)
        stock.save
      end
    rescue => exception
      flash[:alert] = "The server is not responding correctly for the time being. Please try again later."
      redirect_to root_path
    end
  end

  # Method that returns the full name of a user or Anonymous if they choose not to have any name
  def full_name
    return "#{first_name} #{last_name}" if !first_name.empty? || !last_name.empty?
    "Anonymous"
  end

  # Search User/Friends methods

  def self.matches(field_name, param)
    # This returns an ActiveRecord::Relation in the console
    where("#{field_name} like ?", "%#{param}%")
  end

  def self.first_name_matches(param)
    matches("first_name", param)
  end

  def self.last_name_matches(param)
    matches("last_name", param)
  end

  def self.email_matches(param)
    matches("email", param)
  end

  def self.search(param)
    param.strip!
    # Concatenating this methods returns an array of user's objects
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless !to_send_back.empty?
    to_send_back
  end

  # Method that runs through friends and exclude the current user if present
  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  # It checks if the id of the searched user is already in the current user's friends
  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    current_user.friendships.build(friend_id: params[:friend])
    if current_user.save
      flash[:notice] = "Following friend"
    else
      flash[:alert] = "There was something wrong with the tracking request"
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Stopped following"
    redirect_to my_friends_path
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock].upcase)
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol to search"
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search"
        format.js { render partial: 'users/result' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @user = current_user
    if !current_user.stocks.empty?
      current_user.update_stock_prices
    end
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @followed_friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    if !@user.stocks.empty?
      @user.update_stock_prices
    end
    @tracked_stocks = @user.stocks
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      if !@friends.nil?
        @friends = current_user.except_current_user(@friends)
      end
      if !@friends.nil? && !@friends.empty?
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Email</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @followed_friends.each do |friend| %>
          <tr>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>
            <td><%= friend.email %></td>
            <td>
              <%= link_to 'View Profile', user_path(friend), class: "btn btn-info btn-sm" %>
              <%= link_to 'Stop following', 
                  friendship_path(friend), 
                  method: :delete, 
                  data: {confirm: 'Are you sure?'}, 
                  class: "btn btn-warning btn-sm" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-3 bg-light text-body">
  <div class="container text-center">
    <small>Web App developed by <%= link_to 'Matías Rodríguez', "https://github.com/mati-rodriguez80", class: "bg-light text-body" %> 
    | The Complete Ruby on Rails Developer Course | Udemy
    </small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'FinanceTracker', root_path, class: "navbar-brand" %>
    <% if user_signed_in? %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if request.path == root_path %>
            <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
              <!-- Button trigger modal -->
              <a type="button" class="nav-link" data-toggle="modal" data-target="#exampleModal">My Portfolio</a>

              <!-- Modal -->
              <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Loading Your Portfolio</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      We are going to update your stock's prices. This could take up to a few seconds. 
                      Same thing is going to happen when viewing a User/Friend's profile.
                    </div>
                    <div class="modal-footer">
                      <div class="collapse width" id="collapseWidthExample">
                        <div class="spinner-border text-info" role="status">
                          <span class="sr-only">Loading...</span>
                        </div>
                      </div>
                      <%= link_to(my_portfolio_path) do %>
                        <button class="btn btn-outline-info" type="button" data-toggle="collapse" data-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
                          Go to My Portfolio
                        </button>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </li>
          <% else %>
            <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
              <%= link_to 'My Portfolio', my_portfolio_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
            <%= link_to 'My Friends', my_friends_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <%= fa_icon "edit" %> Edit Profile
              <% end %>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item user-name">
            <%= fa_icon "user" %> <%= current_user.full_name %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, class: "btn btn-danger logout-button", method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div class="container" id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
    <h3>Tracked Stocks</h3>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td>
              <% if current_user.can_track_stock?(stock.ticker) %>
                <%= link_to 'Add to portfolio', 
                    user_stocks_path(user: current_user, ticker: stock.ticker), 
                    class: "btn btn-success btn-sm", 
                    method: :post %>
              <% elsif current_user.id != @user.id %>
                <span class="badge badge-secondary">
                  You are already tracking 
                  <% if !current_user.under_stock_limit? && current_user.stock_already_tracked?(stock.ticker) %>
                    10 stocks and this stock
                  <% elsif !current_user.under_stock_limit? %>
                    10 stocks
                  <% elsif current_user.stock_already_tracked?(stock.ticker) %>
                    this stock
                  <% end %>
                </span>
              <% else %>
                <%= link_to 'Remove', 
                    user_stock_path(stock), 
                    method: :delete, 
                    data: {confirm: 'Are you sure?'}, 
                    class: "btn btn-warning btn-sm" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friend_result.html.erb
<div class="flash-results">
  <%= render 'layouts/messages' %>
</div>
<% if !@friends.nil? && !@friends.empty? %>
  <div class="card card-header results-block">
    <table class="col-md-12">
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><strong>Name: </strong><%= friend.full_name %></td>
            <td><strong>Email: </strong><%= friend.email %></td>
            <td>
              <%= link_to 'View Profile', user_path(friend), class: "btn btn-info btn-sm" %>
              <% if current_user.not_friends_with?(friend.id) %>
                <%= link_to 'Follow friend?', 
                    friendships_path(friend: friend), 
                    class: "btn btn-success btn-sm", 
                    method: :post %>
              <% else %>
                <span class="badge badge-secondary">You are friends</span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>';

app/views/users/_result.html.erb
<div class="flash-results">
  <%= render 'layouts/messages' %>
</div>
<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong><%= @stock.ticker %>
    <strong>Name: </strong><%= @stock.name %>
    <strong>Price: </strong><%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', 
          user_stocks_path(ticker: @stock.ticker), 
          class: "btn btn-success", 
          method: :post %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking 
        <% if !current_user.under_stock_limit? && current_user.stock_already_tracked?(@stock.ticker) %>
          10 stocks and this stock
        <% elsif !current_user.under_stock_limit? %>
          10 stocks
        <% elsif current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>';

app/views/users/my_friends.html.erb
<h1>Friends</h1>
<div class="search-area">
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon "search 2x" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="friend-results">
</div>
<% if !@followed_friends.empty? %>
  <%= render 'friends/list' %>
<% else %>
  <div class="row">
    <div class="col-9">
      <p class="lead">You are not following friends yet!</p>
      <em>
        Friends can help you get new investment ideas since you will be able to see which stocks they are tracking.
        Please enter a user's name or email in the search form. You can also look at all the users that are using
        the application if you just enter an <strong>@</strong> symbol.
      </em>
    </div>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="search-area">
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon "search 2x" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>
<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% else %>
  <div class="row">
    <div class="col-9">
      <p class="lead">You are currently not tracking any stocks</p>
      <em>Do not wait to start following them! To do that, please look up for a <strong>Stock Ticker Symbol</strong> in the search form above.</em>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>User Details</h1>
<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Name: </strong><%= @user.full_name %></td>
        <td><strong>Email: </strong><%= @user.email %></td>
        <td>
          <% if current_user.not_friends_with?(@user.id) %>
            <%= link_to 'Follow friend?', 
                friendships_path(friend: @user), 
                class: "btn btn-success btn-sm", 
                method: :post %>
          <% else %>
            <span class="badge badge-secondary">You are friends</span>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>
<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% else %>
  <p class="lead">This user is not tracking any stocks</p>
<% end %>

app/views/welcome/index.html.erb
<h1 class="text-center my-4">Welcome to the Finance Tracker App</h1>

<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active rounded-lg main-img-1">
      <div class="carousel-caption d-none d-md-block">
        <h3 class="text-body mb-4"><strong>Improve Your Finance</strong></h3>
        <p class="text-body"><strong>Keep track of the Stock Market and make the right decisions.</strong></p>
      </div>
    </div>
    <div class="carousel-item rounded-lg main-img-2">
      <div class="carousel-caption d-none d-md-block">
        <h3 class="text-white mb-4"><strong>Your Own Up-To-Date Portfolio of Stocks</strong></h5>
        <p class="text-white"><strong>Finance Tracker App will update your stock prices each time you visit your portofolio.</strong></p>
      </div>
    </div>
    <div class="carousel-item rounded-lg main-img-3">
      <div class="carousel-caption d-none d-md-block">
        <h3 class="text-body mb-4"><strong>Let Friends Also Give You a Hand</strong></h3>
        <p class="text-body"><strong>Follow other users that might track stocks that could help you come up with new investment ideas.</strong></p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-target="#carouselExampleCaptions" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-target="#carouselExampleCaptions" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </button>
</div>